Repository newjersey/navigator.business.nj.gov, pull requests merged in 2022-02, with the labels that each got.

#1508 fix: updating Tasks apply-scorp-federal
  content/src/roadmaps/tasks/apply-scorp-federal.md
Labels: netlify-cms/pending_publish

#1512 fix: updating Contextual Information entity-id
  content/src/display-content/contextual-information/entity-id.md
Labels: netlify-cms/pending_publish

#1507 fix: updating Tasks insurance-massage-therapy
  content/src/roadmaps/tasks/insurance-massage-therapy.md
Labels: netlify-cms/pending_publish

#1509 fix: updating Tasks apply-scorp-state
  content/src/roadmaps/tasks/apply-scorp-state.md
Labels: netlify-cms/pending_publish

#1526 fix: updating Oscar Onboarding Content existing-employees
  content/src/display-content/onboarding/owning/existing-employees.md
Labels: netlify-cms/pending_publish

#1527 fix: updating Oscar Onboarding Content date-of-formation
  content/src/display-content/onboarding/owning/date-of-formation.md
Labels: netlify-cms/pending_publish

#1450 chore: creating Industry Roadmaps massage-therapy
  content/src/roadmaps/industries/massage-therapy.json
Labels: netlify-cms/pending_publish

#1565 fix: updating Oscar Onboarding Content municipality
  content/src/display-content/onboarding/owning/municipality.md
Labels: netlify-cms/pending_publish

#1532 fix: updating Contextual Information registered-agent
  content/src/display-content/contextual-information/registered-agent.md
Labels: netlify-cms/pending_publish

#1568 fix: updating Poppy Onboarding Content municipality
  content/src/display-content/onboarding/starting/municipality.md
Labels: netlify-cms/pending_publish

#1569 chore: creating Contextual Information foreign-business
  content/src/display-content/contextual-information/foreign-business.md
Labels: netlify-cms/pending_publish

#1539 fix: updating Funding Opportunities Content premier-community-development
  content/src/opportunities/premier-community-development.md
Labels: netlify-cms/pending_publish

#1552 fix: updating Funding Opportunities Content small-business-fund
  content/src/opportunities/small-business-fund.md
Labels: netlify-cms/pending_publish

#1553 fix: updating Funding Opportunities Content small-business-improvement
  content/src/opportunities/small-business-improvement.md
Labels: netlify-cms/pending_publish

#1554 fix: updating Funding Opportunities Content small-business-lease
  content/src/opportunities/small-business-lease.md
Labels: netlify-cms/pending_publish

#1598 fix: updating Funding Opportunities Content small-business-improvement
  content/src/opportunities/small-business-improvement.md
Labels: netlify-cms/pending_publish

#1601 fix: updating Funding Opportunities Content small-business-lease
  content/src/opportunities/small-business-lease.md
Labels: netlify-cms/pending_publish

#1555 fix: updating Funding Opportunities Content the-small-business
  content/src/opportunities/the-small-business.md
Labels: netlify-cms/pending_publish

#1604 fix: updating Funding Opportunities Content veteran-owned-business
  content/src/opportunities/veteran-owned-business.md
Labels: netlify-cms/pending_publish

#1612 fix: updating Funding Opportunities Content veteran-owned-business
  content/src/opportunities/veteran-owned-business.md
Labels: netlify-cms/pending_publish

#1540 fix: updating Funding Opportunities Content premier-lender-program
  content/src/opportunities/premier-lender-program.md
Labels: netlify-cms/pending_publish

#1614 fix: updating Funding Opportunities Content small-business-improvement
  content/src/opportunities/small-business-improvement.md
Labels: netlify-cms/pending_publish

#1613 fix: updating Funding Opportunities Content small-business-fund
  content/src/opportunities/small-business-fund.md
Labels: netlify-cms/pending_publish

#1627 fix: updating Oscar Onboarding Content date-of-formation
  content/src/display-content/onboarding/owning/date-of-formation.md
Labels: netlify-cms/pending_publish

#1629 fix: updating Oscar Onboarding Content date-of-formation
  content/src/display-content/onboarding/owning/date-of-formation.md
Labels: netlify-cms/pending_publish

#1641 feat: [#1471] visually identify required tasks on roadmap and task screen
  web/public/img/required-task-icon.svg
  web/public/mgmt/config.yml
  web/src/components/Step.tsx
  web/src/components/Task.test.tsx
  web/src/components/Task.tsx
  web/src/components/TaskHeader.tsx
  web/src/components/njwds-extended/Tag.tsx
  web/src/components/njwds-extended/__snapshots__/Tag.test.tsx.snap
  web/src/display-defaults/tasks/TaskDefaults.ts
  web/src/lib/types/types.ts
  web/src/lib/utils/helpers.tsx
  web/src/lib/utils/markdownReader.ts
  web/test/factories.ts
  web/test/pages/[taskUrlSlug].test.tsx
  web/test/pages/roadmap.test.tsx
Labels: (:star: )

#1659 chore: creating Archived Funding Opportunities Content mwbe
  content/src/archived-opportunities/mwbe.md
Labels: netlify-cms/pending_publish

#1665 fix: updating Funding Opportunities Content veteran-owned-business
  content/src/opportunities/veteran-owned-business.md
Labels: netlify-cms/pending_publish

#1666 chore: creating Contextual Information women
  content/src/display-content/contextual-information/women.md
Labels: netlify-cms/pending_publish

#1667 chore: creating Contextual Information minority
  content/src/display-content/contextual-information/minority.md
Labels: netlify-cms/pending_publish

#1661 fix: updating Archived Funding Opportunities Content mwbe
  content/src/archived-opportunities/mwbe.md
Labels: netlify-cms/pending_publish

#1660 chore: creating Archived Funding Opportunities Content dvob
  content/src/archived-opportunities/dvob.md
Labels: netlify-cms/pending_publish

#1668 fix: updating Tasks register-for-ein
  content/src/roadmaps/tasks/register-for-ein.md
Labels: netlify-cms/pending_publish

#1669 fix: updating Tasks register-for-ein
  content/src/roadmaps/tasks/register-for-ein.md
Labels: netlify-cms/pending_publish

#1651 fix: updating Funding Opportunities Content premier-lender-program
  content/src/opportunities/premier-lender-program.md
Labels: netlify-cms/pending_publish

#1662 chore: creating Archived Funding Opportunities Content sbe
  content/src/archived-opportunities/sbe.md
Labels: netlify-cms/pending_publish

#1602 fix: updating Archived Funding Opportunities Content nj-industry-partnerships
  content/src/archived-opportunities/nj-industry-partnerships.md
Labels: netlify-cms/pending_publish

#1689 fix: updating Tasks license-accounting
  content/src/roadmaps/tasks/license-accounting.md
Labels: netlify-cms/pending_publish

#1694 fix: updating Contextual Information legal-structure-learn-more
  content/src/display-content/contextual-information/legal-structure-learn-more.md
Labels: netlify-cms/pending_publish

#1704 fix: updating Archived Funding Opportunities Content sbe
  content/src/archived-opportunities/sbe.md
Labels: netlify-cms/pending_publish

#1690 fix: updating Tasks register-firm-accounting
  content/src/roadmaps/tasks/register-firm-accounting.md
Labels: netlify-cms/pending_publish

#1713 fix: updating Business Formation business-address-line1
  content/src/display-content/business-formation/business-address-line1.md
Labels: netlify-cms/pending_publish

#1723 fix: updating Business Formation registered-agent
  content/src/display-content/business-formation/registered-agent.md
Labels: netlify-cms/pending_publish

#1714 fix: updating Business Formation registered-agent-number
  content/src/display-content/business-formation/registered-agent-number.md
Labels: netlify-cms/pending_publish

#1717 fix: updating Business Formation contact-information
  content/src/display-content/business-formation/contact-information.md
Labels: netlify-cms/pending_publish

#1726 fix: updating Business Formation doc-certified-copy-of-formation-document
  content/src/display-content/business-formation/doc-certified-copy-of-formation-document.md
Labels: netlify-cms/pending_publish

#1727 fix: updating Business Formation opt-in-annual-report
  content/src/display-content/business-formation/opt-in-annual-report.md
Labels: netlify-cms/pending_publish

#1729 fix: updating Business Formation services
  content/src/display-content/business-formation/services.md
Labels: netlify-cms/pending_publish

#1728 fix: updating Business Formation opt-in-corp-watch
  content/src/display-content/business-formation/opt-in-corp-watch.md
Labels: netlify-cms/pending_publish

#1685 chore: creating Industry Roadmaps marketing-consulting
  content/src/roadmaps/industries/marketing-consulting.json
Labels: netlify-cms/pending_publish

#1693 chore: creating Industry Roadmaps pr-consultant
  content/src/roadmaps/industries/pr-consultant.json
Labels: netlify-cms/pending_publish

#1732 chore: creating Business Formation form-business-entity-intro
  content/src/display-content/business-formation/form-business-entity-intro.md
Labels: netlify-cms/pending_publish

#1742 fix: updating Business Formation doc-official-formation
  content/src/display-content/business-formation/doc-official-formation.md
Labels: netlify-cms/pending_publish

#1743 fix: updating Business Formation doc-certificate-of-standing
  content/src/display-content/business-formation/doc-certificate-of-standing.md
Labels: netlify-cms/pending_publish

#1753 chore: creating Industry Roadmaps management-consulting
  content/src/roadmaps/industries/management-consulting.json
Labels: netlify-cms/pending_publish

#1781 fix: updating Industry Roadmaps cosmetology
  content/src/roadmaps/industries/cosmetology.json
Labels: netlify-cms/pending_publish

#1776 fix: updating Tasks apply-for-shop-license
  content/src/roadmaps/tasks/apply-for-shop-license.md
Labels: netlify-cms/pending_publish

#1777 fix: updating Tasks apply-scorp-federal
  content/src/roadmaps/tasks/apply-scorp-federal.md
Labels: netlify-cms/pending_publish

#1778 fix: updating Tasks apply-scorp-state
  content/src/roadmaps/tasks/apply-scorp-state.md
Labels: netlify-cms/pending_publish

#1782 fix: updating Tasks building-permit
  content/src/roadmaps/tasks/building-permit.md
Labels: netlify-cms/pending_publish

#1784 fix: updating Tasks site-safety-permits-cosmetology
  content/src/roadmaps/tasks/site-safety-permits-cosmetology.md
Labels: netlify-cms/pending_publish

#1783 fix: updating Tasks business-plan
  content/src/roadmaps/tasks/business-plan.md
Labels: netlify-cms/pending_publish

#1799 chore: creating Contextual Information poi-cannabis
  content/src/display-content/contextual-information/poi-cannabis.md
Labels: netlify-cms/pending_review

#1801 chore: creating Contextual Information sip-cannabis
  content/src/display-content/contextual-information/sip-cannabis.md
Labels: netlify-cms/pending_publish

#1798 chore: creating Contextual Information impactzonebusiness-cannabis
  content/src/display-content/contextual-information/impactzonebusiness-cannabis.md
Labels: netlify-cms/pending_review

#1795 chore: creating Contextual Information microbusiness-cannabis
  content/src/display-content/contextual-information/microbusiness-cannabis.md
Labels: netlify-cms/pending_review

#1797 chore: creating Contextual Information diverslyownedbusiness-cannabis
  content/src/display-content/contextual-information/diverslyownedbusiness-cannabis.md
Labels: netlify-cms/pending_publish

#1796 chore: creating Contextual Information socialequitybusiness-cannabis
  content/src/display-content/contextual-information/socialequitybusiness-cannabis.md
Labels: netlify-cms/pending_publish

#1878 fix: updating Certification Opportunities Content mwbe
  content/src/certifications/mwbe.md
Labels: netlify-cms/pending_publish

#1879 fix: updating Certification Opportunities Content dvob
  content/src/certifications/dvob.md
Labels: netlify-cms/pending_publish
